version: "3.7"

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: polito
      POSTGRES_USER: fabio
    ports:
      - 5432:5432
    volumes:
      - $XDG_DATA_HOME/postgresql/data:/var/lib/postgresql/data

  adminer:
    image: adminer
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    depends_on:
      - postgres
    ports:
      - 8080:8080

  php-apache:
    build: .
    depends_on:
      - postgres
    ports:
      - 80:80
    volumes:
      - $PROJECTS_FOLDER/phpwebapp:/var/www/html
