version: "3.7"

services:
  postgres:
    image: postgres
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - $XDG_DATA_HOME/postgresql/data:/var/lib/postgresql/data

  adminer:
    image: adminer
    env_file:
      - .env
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    depends_on:
      - postgres
    ports:
      - 8080:8080

  php-apache:
    build: .
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - 80:80
    volumes:
      - $PROJECTS_FOLDER/phpwebapp:/var/www/html
    links:
      - postgres:db
