version: "3.9"

services:

  nginx:
    hostname: nginx
    image: nginx:alpine
    restart: always
    network_mode: host
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www/letsencrypt:/var/www/letsencrypt:ro
      - /var/cache/pacman/pkg:/pkgcache:ro  
