version: "3.9"

services:

  react_ultimate_resume:
    image: eathtespagheti/react-ultimate-resume
    user: 1000:1000
    ports: 
      - 10012:3000
    volumes: 
      - ../react_ultimate_resume/json_stub.json:/react-ultimate-resume/src/data/json_stub.json
