version: "3.9"

services:
  
  mariadb:
    image: mariadb
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    command: mysqld --transaction-isolation=READ-COMMITTED --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=512 --innodb-rollback-on-timeout=OFF --innodb-lock-wait-timeout=50
    volumes:
      - /run/media/fabio/Configs/mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql-root
      - MYSQL_PASSWORD_FILE=/run/secrets/mysql-user
      - MYSQL_DATABASE=photoprism
      - MYSQL_USER=photoprism
    secrets:
      - mysql-root
      - mysql-user

  photoprism:
    hostname: Photoprism
    image: thielepaul/photoprism:db-api
    restart: unless-stopped
    ports:
      - 10003:80
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    env_file:
      - ../secrets/photoprism.env
    environment:
      - PHOTOPRISM_HTTP_PORT=80
      - PHOTOPRISM_HTTP_COMPRESSION=gzip
      - PHOTOPRISM_DEBUG=false
      - PHOTOPRISM_PUBLIC=false
      - PHOTOPRISM_READONLY=false
      - PHOTOPRISM_EXPERIMENTAL=true
      - PHOTOPRISM_DISABLE_WEBDAV=false
      - PHOTOPRISM_DISABLE_SETTINGS=false
      - PHOTOPRISM_DISABLE_TENSORFLOW=false
      - PHOTOPRISM_DARKTABLE_PRESETS=false
      - PHOTOPRISM_DETECT_NSFW=true
      - PHOTOPRISM_UPLOAD_NSFW=true
      - PHOTOPRISM_DATABASE_DRIVER=mysql
      - PHOTOPRISM_DATABASE_SERVER=mariadb:3306
      - PHOTOPRISM_DATABASE_NAME=photoprism
      - PHOTOPRISM_DATABASE_USER=photoprism
      - PHOTOPRISM_SITE_URL=https://photos.eathtespagheti.eu
      - PHOTOPRISM_SITE_TITLE=PhotoPrism
      - PHOTOPRISM_SITE_CAPTION=Browse Your Life
      - PHOTOPRISM_SITE_DESCRIPTION=xPHOTOSx
      - PHOTOPRISM_SITE_AUTHOR=eathtespagheti
      - PHOTOPRISM_SPONSOR=true
    user: 1000:1000
    depends_on: 
      - mariadb
      - nginx
    volumes:
      - /run/media/fabio/Photoprism:/photoprism/storage
      - /run/media/fabio/Nextcloud/data/fabio/files/Pictures:/photoprism/originals

secrets:
  mysql-root:
    file: ../secrets/mysql-root
  mysql-user:
    file: ../secrets/mysql-user
