version: "3.8"

services:
  # Databases
  db:
    image: postgres:13.4-alpine
    restart: always
    env_file:
      - ../nextcloud/nextcloud.env
    volumes:
      - /run/media/fabio/Configs/postgres:/var/lib/postgresql/data
    secrets:
      - postgres_password

  redis:
    image: redis:alpine
    restart: always

  smtp:
    image: namshi/smtp
    restart: always
    environment: 
      - CERTIFICATE_PATH=/etc/letsencrypt/live/eathtespagheti.eu/fullchain.pem
      - KEY_PATH=/etc/letsencrypt/live/eathtespagheti.eu/privkey.pem
      - MAILNAME=eathtespagheti.eu
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
  
  nextcloud:
    hostname: xNextcloudx
    image: eathtespagheti/nextcloud
    restart: always
    ports:
      - 10000:80
    env_file:
      - ../nextcloud/nextcloud.env
    environment: 
      - POSTGRES_HOST=db
      - NEXTCLOUD_ADMIN_PASSWORD_FILE=/run/secrets/nextcloud_admin_password
      - NEXTCLOUD_ADMIN_USER=fabio
      - REDIS_HOST=redis
      - NEXTCLOUD_TRUSTED_DOMAINS=localhost 192.168.1.* cloud.eathtespagheti.eu direct.eathtespagheti.eu
      - TRUSTED_PROXIES=192.168.1.* cloud.eathtespagheti.eu direct.eathtespagheti.eu
      - OVERWRITEPROTOCOL=https
      - SMTP_HOST=smtp
      - SMTP_AUTHTYPE=PLAIN
      - MAIL_FROM_ADDRESS=xnextcloudx
      - MAIL_DOMAIN=eathtespagheti.eu
      - PHP_MEMORY_LIMIT=1G
      - PHP_UPLOAD_LIMIT=16G
    volumes:
      - /run/media/fabio/Nextcloud:/var/www/html
      - /run/media/fabio/Twins/Alpha:/media/Alpha
    depends_on:
      - db
      - redis
      - nginx
      - smtp
    secrets:
      - nextcloud_admin_password
      - postgres_password

secrets:
  nextcloud_admin_password:
    file: ../secrets/nextcloud_admin_password
  postgres_password:
    file: ../secrets/postgres_password
