version: "3.9"

services:

  ethminer:
    hostname: BigChameleon
    image: eathtespagheti/ethminer
    user: 1000:1000
    restart: always
    ports:
      - 10005:80
    environment: 
      - SCHEME=stratum1+tcp
      - USERNAME=BigChameleon
      - WORKERNAME=BigChameleon.001
      - POOLADDRESS=ethash.poolbinance.com
      - POOLPORT=1800
      - API_PORT=80
      - RECHECK_TIME=2000
      - PASSWORD=123456
    volumes: 
      - /etc/OpenCL:/etc/OpenCL:ro
      - /usr/lib:/usr/externalibs:ro
      - /opt/amdgpu:/opt/amdgpu:ro
      - /opt/amdgpu-pro:/opt/amdgpu-pro:ro
      - /usr/share/libdrm:/usr/share/libdrm:ro
    devices: 
      - /dev/dri/card1:/dev/dri/card1
      - /dev/dri/renderD129:/dev/dri/renderD129
